name = "sample" # if you change this, make sure to update the path in `index.html`
version = "0.1.0"
description = "a web project"

target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.29"

